<?php

/*********************************************************************
 * Extension configuration file for ext "gkh_rss_import".
 *
 * Generated by ext 15-05-2016 12:01 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'gkh RSS Import',
    'description' => 'Imports a RSS feed and show the content on a FE page.',
    'category' => 'plugin',
    'version' => '6.0.0',
    'state' => 'stable',
    'uploadfolder' => false,
    'createDirs' => 'uploads/tx_gkhrssimport/',
    'clearCacheOnLoad' => true,
    'author' => 'Simon Schaufelberger',
    'author_email' => 'simonschaufi+typo3@gmail.com',
    'author_company' => '',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ]
];
