name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1]
        typo3: [^12.0]

    name: P${{ matrix.php }} - T${{ matrix.typo3 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-typo3-${{ matrix.typo3 }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer require "typo3/cms-core:${{ matrix.typo3 }}" --prefer-dist --no-progress --no-interaction

      - name: Check PHP syntax errors
        run: find . -name \*.php ! -path "./.Build/*" -print0 | xargs -0 -n1 -P4 php -d display_errors=stderr -n -l > /dev/null

      #- name: Run TypoScript linter
      #  run: .Build/bin/typoscript-lint -c .typoscript-lint.yml --fail-on-warnings

      - name: Execute unit tests
        run: .Build/bin/phpunit --colors -c Build/UnitTests.xml --stop-on-failure
        env:
          TYPO3_PATH_WEB: $PWD/.Build/public

      - name: Execute functional tests
        run: .Build/bin/phpunit --colors -c Build/FunctionalTests.xml --stop-on-failure
        env:
          TYPO3_PATH_WEB: $PWD/.Build/public
          typo3DatabaseDriver: pdo_sqlite
